package org.hiram.forms;

import javax.swing.*;
import java.awt.*;

public class Borrower extends JFrame {
    private JPanel borrowedBooksPanel;
    private JPanel borrowPanel;
    private JButton searchButton;
    private JTextField searchTextField;
    private JButton TESTADDButton;

    public Borrower() {
        $$$setupUI$$$();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(borrowPanel);
        pack();
        TESTADDButton.addActionListener(e -> {
            JPanel newRow = createBookEntry();
            borrowedBooksPanel.add(newRow);
            borrowedBooksPanel.revalidate();
            borrowedBooksPanel.repaint();
        });
        setVisible(true);
    }

    private JPanel createBookEntry() {
        JPanel rowPanel = new JPanel(new FlowLayout(FlowLayout.LEFT));

        JTextField inputField = new JTextField(20);
        JTextArea testTextArea = new JTextArea("Title: \nGenre: \nSigned out: 12/31/1969    Due return: 12/31/1969", 3, 1);
        JButton removeButton = new JButton("X");

        removeButton.addActionListener(e -> {
            borrowedBooksPanel.remove(rowPanel);
            borrowedBooksPanel.revalidate();
            borrowedBooksPanel.repaint();
        });
        rowPanel.add(new JLabel("Book"));
        rowPanel.add(testTextArea);
        rowPanel.add(inputField);
        rowPanel.add(removeButton);
        // Constrain height for BoxLayout
        rowPanel.setMaximumSize(new Dimension(Integer.MAX_VALUE, 80));

        return rowPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        borrowPanel = new JPanel();
        borrowPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(4, 4, new Insets(0, 0, 0, 0), -1, -1));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        borrowPanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer2 = new com.intellij.uiDesigner.core.Spacer();
        borrowPanel.add(spacer2, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, 1, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        searchButton = new JButton();
        searchButton.setText("Search");
        borrowPanel.add(searchButton, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchTextField = new JTextField();
        borrowPanel.add(searchTextField, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 2, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        borrowPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        scrollPane1.setViewportView(borrowedBooksPanel);
        TESTADDButton = new JButton();
        TESTADDButton.setText("TEST ADD");
        borrowPanel.add(TESTADDButton, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return borrowPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        borrowedBooksPanel = new JPanel();
        borrowedBooksPanel.setLayout(new BoxLayout(borrowedBooksPanel, BoxLayout.Y_AXIS));
    }
}
